### PR TITLE
Angular 9 migrate

### PR DESCRIPTION
**Pull request by jecraig**
Migrating to Angular 9. The odd sorting bug https://github.com/SortableJS/ngx-sortablejs/issues/189 is not resolved by this migration.

### CODE REVIEW

**Comment by lalogrosz** [comment]
Can you merge this PR? I need support for Angular 9 PLEASE

**Comment by CodingCloud9527** [comment]
has migrated to angular 10

**Comment by lalogrosz** [comment]
> has migrated to angular 10

But Angular 9 was skipped. I needed for Angular 9 too.

**Comment by CodingCloud9527** [comment]
@lalogrosz  I have released a version base on Angular 9. you can install with `yarn add ngx-sortablejs@9.0.0` or `npm install ngx-sortablejs@9.0.0`.

**Pull request closed without merging**
