### PR TITLE
Angular 10 support

### PR DESCRIPTION
**Pull request by bjornharvold**
Very easy patch to support Angular 10

### CODE REVIEW

**Comment by smnbbrv** [comment]
#197

**Comment by BenRacicot** [comment]
Hello, in addition to the ng10 update is ngx-sortableJS up to date with sortableJS?

**Review by shubhamt619 — COMMENTED** [review]
Thank you, please merge ASAP

**Comment by kgish** [comment]
Am also in desperate need of Angular 10 support, please!

**Comment by CodingCloud9527** [comment]
has Migrated to angular 10

**Pull request closed without merging**
